#~/.config/kitty/kitty.conf
# Kitty Terminal configuration file

# Pywal Color Scheme
include ~/.cache/wal/colors-kitty.conf


# Fonts
font_family       JetBrainsMono Nerd Font
font_size         13.0
bold_font         auto
italic_font       auto
bold_italic_font  auto

# Settings
# The modifier keys to press when clicking on URLs to open them.
open_url_modifiers ctrl

# The program used to open URLs when clicked. "default" uses the OS's default handler.
open_url_with default


# Clipboard
map ctrl+v paste_from_clipboard
map ctrl+c copy_to_clipboard

allow_remote_control yes
