# ~/.config/hypr/windowrules.conf

windowrule {
  name = waypaper-popup
  match:class = ^(waypaper)$

  float = on
  size = 300 600
  center = on
  stay_focused = on
}

windowrule {
  name = no-transparency-code
  match:class = ^([Cc]ode.*)$

  opacity = 1.0 override 1.0 override
}

windowrule {
  name = no-transparency-firefox
  match:class = ^(firefox)$

  opacity = 1.0 override 1.0 override
}

windowrule {
  name = no-transparency-librewolf
  match:class = ^([Ll]ibre[Ww]olf)$

  opacity = 1.0 override 1.0 override
}

